---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: s2i-perl-run
spec:
  taskRef:
    name: s2i-perl
  resources:
    outputs:
      - name: image
        resourceRef:
          name: image
    inputs:
      - name: source
        resourceRef:
          name: s2i-perl-ex
  params:
    - name: TLSVERIFY
      value: "false"
    - name: PATH_CONTEXT
      value: "examples/sample-test-app"
